# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20170824_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
