# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
