# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_remove_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lng',
        ),
    ]
