# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20170905_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
