# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20170905_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
